name: touch_mouse_behavior
description: Scroll behavior to support both Touch and Mouse for web in scrollable widgets.
version: 0.0.2
homepage: https://github.com/javaherisaber/touch_mouse_behavior

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
